### ISSUE TITLE
Project Goals

### ISSUE THREAD

**Issue by meffij** [PsiLupan/FRAY#3]
What does building this project produce? (I assume a GameCube iso)

What are the goals of this project?

How can I help?

**Comment by PsiLupan** [comment]
Sorry, don't have notifications enabled here, so just saw your issue post.

Currently, the goal is getting the game working on a GameCube (support for Wii is also currently possible, the only technical limitation is the inability to use MEM2 without a custom allocator).

The biggest help right now would just be contributing, whether that's reverse engineering functions or even providing adequate names for functions. Likewise, I use the community documentation (and add to it myself), so any additions there for various structs are always appreciated.

**Comment by JayFoxRox** [comment]
I'm also confused about what building this project produces. It seems to be a dol executable.

- How do you test this project?
- Is there an option to build this as a hook that can be loaded into dolphin-emu?
- Is there a patcher so the game functions are hooked (so it runs, even though the project is incomplete)?
- Are there any plans for recompilation from PowerPC to other architectures (such as LLVM / object files) to allow cross compilation?
- Are there any statistics as to how far along this project is?
- Are there any plans for C++ (I prefer C; although there might be benefits in C++)?
- What's the differentiation from https://github.com/filfat/openmelee ?

*(Just for your information: I don't intend to work on this, I'm just curious)*

**Comment by filfat** [comment]
@JayFoxRox I can answer the last question. openmelee was (is?) an attempt from me to re-implement melee’s game logic while doing everything else from the ground up. While this is (afaik) an attempt at a 1-1 recreation of melee based on RE.

You’ll probably see way more progress from FRAY since I am extremely busy with politics and work at the moment.

(And tbh I’ll probably archive openmelee and instead contribute to this in the future. 😄)

**Comment by PsiLupan** [comment]
@JayFoxRox

* I test via Dolphin's debugger currently. -O2 executables provide enough for me to trace, but O0 is preferred.

* You can open the DOL with Dolphin's open option. Presently, there's some missing function prototypes that block -O0 compilation.

* That'd require not targeting GX. I don't really know graphics APIs well enough to do that myself.

* I haven't been tracking it in a while, but I know off-hand the title screen needed just a bit more work to load. HAL Sysdolphin was also about ~75% complete and was most of what was needed.

* I don't really plan to presently. Smart pointers to cleanup the ref counting code and turning HSD into formal classes (versus their classes in C attempt) are really the only perceived benefits for me at present. I've got a private project where I've started that, but that relies mostly in re-architecting that currently takes too much time.

* As filfat noted, this is mostly an attempt at a formal RE, so rewriting and properly naming everything versus recreating all the logic from scratch. It allows people to pull out functions for modding with the end-goal of being a compilable, trimmed down version of the game.
