### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by filfat** [PsiLupan/FRAY#8]
I would personally strongly recommend going with MIT.
However this might be one of those few cases where a copy-left license makes sense and if so MPL 2.0 is the best choice; it is entirely compatible with GPL but is (in my opinion) a lot more permissive towards developers.

**Comment by PsiLupan** [comment]
I'll have to reference some other projects, like PRET or LADX Disassembly.

Frankly, I find this project in such a legally gray area that it comes across to me as licensing someone else's code in practice. However, they have disasm and packed assets, whereas this does not, so I'm unsure.

**Comment by PsiLupan** [comment]
License is added now. 

I elected to use The Unlicense, as it's the least restrictive while removing liability and other projects such as Devilution use it.
